/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   bottom-sheet.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/elements/dom-if.d.ts" />
/// <reference path="../iron-a11y-announcer/iron-a11y-announcer.d.ts" />
/// <reference path="../polymer/types/lib/legacy/class.d.ts" />
/// <reference path="../iron-overlay-behavior/iron-overlay-behavior.d.ts" />
/// <reference path="../paper-styles/paper-styles.d.ts" />

declare namespace UiElements {

  /**
   * Material design: [Bottom sheets](https://material.google.com/components/bottom-sheets.html#)
   *
   * # `<bottom-sheet>`
   *
   * Bottom sheets slide up from the bottom of the screen to reveal more content.
   *
   * ### Example
   *
   * ```html
   * <bottom-sheet>
   *    <paper-icon-item>
   *      <iron-icon src="inbox.png" item-icon></iron-icon>
   *      Inbox
   *    </paper-icon-item>
   *    <paper-icon-item>
   *      <iron-icon src="keep.png" item-icon></iron-icon>
   *      Keep
   *    </paper-icon-item>
   *    <paper-icon-item>
   *      <iron-icon src="hangouts.png" item-icon></iron-icon>
   *      Hangouts
   *    </paper-icon-item>
   *  </bottom-sheet>
   * ```
   *
   * ### Positioning
   *
   * Use the `fit-bottom` class to position the bar at the bottom of the app and with full width;
   *
   * Use `center-bottom` class to display the bar at the bottom centered on a page.
   *
   * ### Styling
   *
   * `<bottom-sheet>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--bottom-sheet-background-color` | The bottom-sheet background-color | `#fff`
   * `--bottom-sheet-color` | The bottom-sheet color | `#323232`
   * `--bottom-sheet-max-width` | Max width of the element | ``
   * `--bottom-sheet-max-height` | Max heigth of the element | ``
   * `--bottom-sheet-label-color` | Color of the label | `rgba(0, 0, 0, 0.54)`
   * `--bottom-sheet-box-shadow` | Box shaddow property of the element | `0 2px 5px 0 rgba(0, 0, 0, 0.26)`
   */
  class BottomSheet extends
    Polymer.IronOverlayBehavior(
    Object) {

    /**
     * Returns the scrolling element.
     *        
     */
    readonly scrollTarget: any;

    /**
     * The element to fit `this` into.
     * Overridden from `Polymer.IronFitBehavior`.
     */
    fitInto: object|null|undefined;

    /**
     * The label of the bottom sheet.
     */
    label: string|null|undefined;
    sizingTarget: object|null|undefined;

    /**
     * If set the padding won't be added to the scrollable element.
     */
    noPadding: boolean|null|undefined;

    /**
     * True if the overlay is currently displayed.
     */
    opened: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;
    _openedChanged(): void;

    /**
     * Overridden from `IronOverlayBehavior`.
     */
    _renderOpened(): void;

    /**
     * Overridden from `IronOverlayBehavior`.
     */
    _renderClosed(): void;
  }
}

interface HTMLElementTagNameMap {
  "bottom-sheet": UiElements.BottomSheet;
}
